name: 'PyPi Poetry Publish'
description: 'Opinionated GitHub action to fully automate publishing packages to any PyPI registry - using Poetry and GitHub releases'

inputs:
  PACKAGE_DIRECTORY:
    description: 'Directory of the package'
    required: true
  ACTIONS_ACCESS_TOKEN:
    description: 'Access Token for GitHub with write access'
    required: true
  PYTHON_VERSION:
    description: 'Python Version'
    required: false
  PYPI_PASSWORD:
    description: 'Password for the user to publish to PyPi. May also be a Token - requires the `PYPI_USERNAME` to be `__token__`'
    required: true
  PYPI_USERNAME:
    description: 'The username for the registry. Defaults to __token__'
    required: false
    default: '__token__'
  BRANCH:
    description: 'Branch to publish from'
    required: false
    default: 'master'
  REGISTRY:
    description: 'The registry to publish to'
    required: false
    default: 'https://pypi.org/simple/'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.BRANCH }}
        token: ${{ inputs.ACTIONS_ACCESS_TOKEN }}
        path: ./repository

    - name: Install poetry
      run: pip install poetry poetry-core
      shell: bash

    - name: Set up Python ${{ inputs.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: 'poetry'
        check-latest: true

    - name: Set GitHub Tag as Package Version
      run: |
        cd repository
        echo __version__="'"${{ github.event.release.tag_name }}"'" > ${{ inputs.PACKAGE_DIRECTORY }}__init__.py
        sed -i '0,/version =.*/s//version = "'"${{ github.event.release.tag_name }}"'"/' ./pyproject.toml
      shell: bash

    - name: Add and Commit Version
      run: |
        cd repository 
        git add ${{ inputs.PACKAGE_DIRECTORY }}__init__.py ./pyproject.toml
        git config --global user.name "PyPi Poetry Publish Bot"
        git config --global user.email "admin@code-specialist.com"
        git commit -m "Change version to ${{ github.event.release.tag_name }}" --allow-empty
        git push origin HEAD:${{ inputs.BRANCH }}
      shell: bash

    - name: Install Dependencies
      run: |
        cd repository
        poetry install
      shell: bash

    - name: Build and Publish
      run: |
        cd repository
        poetry publish -p ${{ inputs.PYPI_PASSWORD }} -u ${{ inputs.PYPI_USERNAME }} -r ${{ inputs.REGISTRY }} --build
      shell: bash